services:
  frontend:
    image: madhumathibganeshappa/quickbite-frontend:${IMAGE_TAG:-latest}
    container_name: quickbite-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - quickbite-network
    restart: unless-stopped

  backend:
    build: ./app/backend
    container_name: quickbite-backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - quickbite-network
    restart: unless-stopped

  database:
    image: mysql:8.0
    container_name: quickbite-database
    environment:
      MYSQL_ROOT_PASSWORD: quickbite_root
      MYSQL_DATABASE: quickbite
    volumes:
      - ./app/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quickbite-network
    restart: unless-stopped

networks:
  quickbite-network:
    driver: bridge
